language: node_js
repo_token: CVOERALLS.IO_TOKEN
node_js:
- 0.1
before_install:
- openssl aes-256-cbc -K $encrypted_b98699788c3d_key -iv $encrypted_b98699788c3d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
before_script:
- npm install -g grunt-cli
- mv -fv out/ ssh_config ~/.ssh/config
script:
- git remote add deploy root@excel-inc.acmr.com.cn:20065/usr/local/apache2/htdocs/git/test.git
- git push deploy master
