language: java
jdk:
  - oraclejdk7  
#  - openjdk7  
#  - openjdk6  

before_install:
- openssl aes-256-cbc -K $encrypted_6a1d2f835532_key -iv $encrypted_6a1d2f835532_iv
  -in tools/deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- echo skipped

install:
- echo skipped

before_script:
- mv -fv tools/deploy/ssh_config ~/.ssh/config

script:
- mvn install -Dmaven.javadoc.skip=true
notifications:
  email:
    recipients:
    - jinhr@acmr.com.cn

after_script:
