language: java
jdk:
  - oraclejdk7  
#  - openjdk7  
#  - openjdk6  

before_install:

install:
- echo skipped

before_script:
- mv -fv tools/deploy/ssh_config ~/.ssh/config

script:
- mvn install -Dmaven.javadoc.skip=true
notifications:
  email:
    recipients:
    - jinhr@acmr.com.cn

after_script:
