FORMAT: 1A
HOST: http://excel-inc.acmr.com.cn/0.5.3/

# Online excel API document

在线Excel接口文档.

**注意：** 对行列操作时别名最大值用MAX表示。
 


# Group Excel操作
excel操作

## excel新建 [/excel/create]
    url:/excel.htm?m=create

### 新建Excel [POST]
    
+ Request (application/json)

        {
            "name":"excel名称"
        }


+ Response 200 (application/json)

        {
            "excelId":"Id"
        }


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }  


## excel名称修改 [/excel/update]
    url:/excel.htm?m=update

### 修改Excel名称 [POST]
    
+ Request (application/json)

        {   
            "excelId":"Id",
            "name":"excel名称"
        }


+ Response 200 (application/json)



+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 


## excel 加载 [/excel/reload]
    url:/excel.htm?m=reload

### excel加载 [GET]
    
+ Request (application/json)

        {   
            "excelId":"Id"
        }


+ Response 200 (application/json)

        {
            "excelObj": "json对象，包含excel信息"
        }


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## execl下载 [/execl/download]

    url:/excel.htm?m=dwonload

### excel下载 [POST]

+ Request (application/json)

        {   
            "excelId":"Id"
        }


+ Response 200 (application/json)

+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## execl关闭 [/execl/close]

    url:/execl/close/{excelId}/{startX}/{startY}

### excel 关闭 [POST]

+ Request (application/json)

            
        "excelId"="Id"+ "&startX"="x轴开始别名"+"&startY"="y轴开始别名"
        

+ Response 200 (application/json)

+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

# Group Sheet

## Sheet操作 [/sheet/create]
    url:/sheet.htm?m=create

### 新建sheet [POST]

+ Request (application/json)

        {   
            "excelId": "excelId",
            "sheetName": "sheet名称"
        }

+ Response 200 (application/json)


        {
            "sheetId":"sheetId"
        }

+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 修改sheet [/sheet/update]
    url:/sheet.htm?m=update 

### 修改sheet [POST]

+ Request (application/json)

        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "sheetName": "新sheet名称"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 删除sheet [/sheet/delete]

    url:/sheet.htm?m=delete

### 删除sheet [POST]

+ Request (application/json)

        {
            "excelId": "excelId",
            "sheetId": "sheetId"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 冻结 [/sheet/frozen]

    url:/sheet/frozen/{excelId}/{sheetId}/{frozenX}/{frozenY}/{startX}/{startY}

### 冻结 [POST]

+ Request (application/json)

    
        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "frozenX":"frozenX",
            "frozenY":"frozenY",
            "startX" : "startX",
            "startY" : "startY"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

# Group 行列操作

## 插入行 [/cells/rows/insert]
    url:/cells.htm?m=rows_insert

### 插入行 [POST]

+ Request (application/json)

        {   
            "excelId": "excelId",
            "rowAlias": "行别名"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 删除行 [/cells/rows/delete]
    url:/cells.htm?m=rows_delete

### 删除行 [POST]
    
+ Request (application/json)

        {
            "excelId": "excelId",
            "rowAlias": "行别名"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 

## 插入列 [/cells/cols/insert]
    url:/cells.htm?m=cols_insert

### 插入列 [POST]

+ Request (application/json)

        {   
            "excelId": "excelId",
            "colAlias": "列别名"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 删除列 [/cells/cols/delete]
    url:/cells.htm?m=cols_delete

### 删除列 [POST]
    
+ Request (application/json)

        {
            "excelId": "excelId",
            "colAlias": "列别名"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 

# Group 单元格操作

## 创建单元格 [/cells/create]
    url:/cells.htm?m=create

### 创建单元格 [POST]

+ Request (application/json)
        
        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名"
                         }
        }
+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }


## 单元格合并 [/cells/merge]
    url:/cells.htm?m=merge

### 合并 [POST]

+ Request (application/json)

        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名",
                            endX:"X轴结束别名",
                            endY:"Y轴结束别名"
                        }

        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 单元格拆分 [/cells/merge/delete]
    url:/cells.htm?m=merge_delete

### 拆分 [POST]

+ Request (application/json)

        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名",
                            endX:"X轴结束别名",
                            endY:"Y轴结束别名"
                        }
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 边框操作 [/cells/frame]
    url:/cells.htm?m=frame    

### 添加边框 [POST]
    
添加单元格边框

+ Request (application/json)

        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名",
                            endX:"X轴结束别名",
                            endY:"Y轴结束别名"
                        }
            "frameStyle":"参数说明：'left: 左边框,right: 右边框,top：上边框,bottom：下边框,all：所有边框,outer：外边框,none:无边框'"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 水平对齐 [/cells/align/level]
    url:/cells.htm?m=align_level

### 设置单元格对齐方法 [POST]
    
数据对齐方式

+ Request (application/json)
        
        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名",
                            endX:"X轴结束别名",
                            endY:"Y轴结束别名"
                        },
            "alignStyle" : "left：左对齐 right: 右对齐 middle：水平居中"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }


## 垂直对齐 [/cells/align/vertical]
    url:/cells.htm?m=align_vertical

### 设置单元格对齐方法 [POST]
    
设置单元格内容数据对齐方式

+ Request (application/json)
        
        {
            "excelId": "excelId",
            "sheetId": "sheetId",
            "coordinate":{
                            startX:"X轴开始别名",
                            startY:"Y轴开始别名",
                            endX:"X轴结束别名",
                            endY:"Y轴结束别名"
                        },
            "alignStyle" : " top: 顶端对齐 bottom：底端对齐 middle:垂直居中"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }


## 宽度调整 [/cells/cols/width]
    url:/cells.htm?m=cols_width

### 宽度修改 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "colIndex": "列别名",
            "width": "列宽度"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 高度调整 [/cells/rows/height]
    url:/cells.htm?m=rows_height

### 高度修改 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "rowIndex": "行别名",
            "height": "行高度"
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }



# Group 文本内容修改

## 字号 [/font/size]
    url:/text.htm?m=font_size

### 字号 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名",
                "endX":"结束X轴别名",
                "endY":"结束Y轴别名"
            },
            "size": "字体大小12px",
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 风格 [/font/family]
    url:/text.htm?m=font_family

### 风格 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名",
                "endX":"结束X轴别名",
                "endY":"结束Y轴别名"
            },
            "family": "字体风格宋体...",
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 粗细 [/font/weight]
    url:/text.htm?m=font_weight

### 粗细 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名",
                "endX":"结束X轴别名",
                "endY":"结束Y轴别名"
            },
            "weight": "字体加粗",
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 斜体 [/font/italic]
    url:/text.htm?m=font_italic

### 斜体[POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名",
                "endX":"结束X轴别名",
                "endY":"结束Y轴别名"
            },
            "style": "字体倾斜italic",
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 字体颜色 [/font/color]
    url:/text.htm?m=font_color

### 字体颜色 [POST]

+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名",
                "endX":"结束X轴别名",
                "endY":"结束Y轴别名"
            },
            "color": "颜色代码（rgb）",
        }

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 编辑单元格中数据内容 [/data]
    

### 输入内容 [POST]
    url:/text.htm?m=data  
 
+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startX":"起始X轴别名",
                "startY":"起始Y轴别名"
            },   
            "content" : "输入内容"    
        }


+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 

## 区域删除 [/data/del]
    

### 区域删除 [POST]
    url:/text.htm?m=data_del  
 
+ Request (application/json)

        {
            "sheetId": "sheetId",
            "coordinate":{
                "startColAlias":"开始列别名",
                "startRowAlias":"开始行别名",
                "endColAlias":"结束列别名",
                "endRowAlias":"结束行别名"
            },   
        }


+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 



## 批量设置备注 [/commentset]
    

### 增加或修改备注 [POST]
    url:/text.htm?m=comment_set  
 
+ Request (application/json)

        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "comment" : "备注内容"  
        } 


+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 批量删除备注 [/commentdel]

  
### 删除备注 [POST]
    url:/text.htm?m=comment_del  
 
+ Request (application/json)

        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            }
        } 


+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }  

## 设置单元格常规格式 [/dataformat/general]
    url:/text.htm?m=data_format
### 设置常规格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "normal"  
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }
 
## 设置单元格文本格式 [/dataformat/text]
    url:/text.htm?m=data_format
### 设置文本格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "text"  
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 

## 设置单元格数字格式 [/dataformat/number]
    url:/text.htm?m=data_format
### 设置数字格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "number",
            "decimalPoint":  2|0 ,
            "thousandPoint":true|false  
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        } 

## 设置单元格日期格式 [/dataformat/date]
    url:/text.htm?m=data_format
### 设置日期格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "date",
            "dateFormat":  "yyyy-MM-dd" 
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 设置单元格货币格式 [/dataformat/currency]
    url:/text.htm?m=data_format
### 设置货币格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "currency",
            "decimalPoint":  2，
            "currencySymbol" :"$"
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

## 设置单元格百分比格式 [/dataformat/percent]
    url:/text.htm?m=data_format 
### 设置百分比格式 [POST]

+ Request (application/json) 
        
        {
            "excelId": "excelId",
            "coordinate":{
                "startRowAlias":"起始行别名",
                "endRowAlias":"结束行别名",
                "startColAlias":"起始列别名",
                "endColAlias":"结束列别名"
            },
            "format" : "percent",
            "decimalPoint":  2
        } 

+ Response 200 (application/json)


+ Response 500 (application/json)

        {
            "error":"返回错误信息"
        }

# Group 剪切板功能  


## 外部复制功能 [/plate/paste]
    url:/plate.htm?m=paste

### 外部复制 [POST]
外部复制功能

+ Request (application/json)

        {
         "excelId":"excelId",
         "sheetId": "sheetId",
         "pasteData":[{"aliasCol":"列别名","aliasRow":"行别名","text":"内容"}]
        }

+ Response 200 (application/json)

+ Response 202 (application/json)

        {
            "error":"返回错误信息"
        }  

## 内部复制功能 [/plate/copy]
    url:/plate.htm?m=copy

### 内部复制 [POST]
外部复制功能

+ Request (application/json)

        {
         "excelId":"excelId",
         "sheetId": "sheetId",
         "orignal":
                {
                    "startColAlias":"开始列别名",
                     "endColAlias":"结束列别名",
                    "startRowAlias":"开始行别名",
                    "endRowAlias":"结束行别名"
                },
         "target":
                    {"colAlias":"列别名"，
                    "rowAlias":"行别名"},
                }

+ Response 200 (application/json)

+ Response 202 (application/json)

        {
            "error":"返回错误信息"
        } 
        
## 剪切功能 [/plate/cut]
    url:/plate.htm?m=cut

### 剪切 [POST]
剪切功能

+ Request (application/json)

        {
         "excelId":"excelId",
         "sheetId": "sheetId",
         "orignal":{"startColAlias":"开始列别名","endColAlias":"结束列别名","startRowAlias":"开始行别名","endRowAlias":"结束行别名"},
             "target":{"colAlias":"列别名"，"rowAlias":"行别名"}
        }

+ Response 200 (application/json)

+ Response 202 (application/json)

        {
            "error":"返回错误信息"
        }